"use client";
import { useEffect, useState } from "react";
type Prompt = Event & { prompt(): Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> };
export function InstallNiaCta({ copy }: { copy: { installNia: string; installInstructionsTitle: string; installStepOne: string; installStepTwo: string; installStepThree: string; close: string } }) {
  const [prompt, setPrompt] = useState<Prompt | null>(null); const [ios] = useState(() => typeof navigator !== "undefined" && /iphone|ipad|ipod/i.test(navigator.userAgent) && /safari/i.test(navigator.userAgent) && !/crios|fxios/i.test(navigator.userAgent)); const [open, setOpen] = useState(false); const [installed, setInstalled] = useState(() => typeof window !== "undefined" && (window.matchMedia("(display-mode: standalone)").matches || (navigator as Navigator & { standalone?: boolean }).standalone === true));
  useEffect(() => { const before = (e: Event) => { e.preventDefault(); setPrompt(e as Prompt); }; const done = () => setInstalled(true); window.addEventListener("beforeinstallprompt", before); window.addEventListener("appinstalled", done); return () => { window.removeEventListener("beforeinstallprompt", before); window.removeEventListener("appinstalled", done); }; }, []);
  if (installed || (!ios && !prompt)) return null;
  const install = async () => { if (ios) return setOpen(true); if (!prompt) return; await prompt.prompt(); if ((await prompt.userChoice).outcome === "accepted") setInstalled(true); setPrompt(null); };
  return <><button type="button" onClick={install} className="inline-flex rounded-full border border-[#d7e4da] px-3 py-2 text-sm font-semibold text-[#255b48] sm:px-4">{copy.installNia}</button>{open ? <div role="dialog" aria-modal="true" aria-labelledby="install-title" className="fixed inset-0 z-50 grid place-items-end bg-[#173b32]/30 p-4 sm:place-items-center"><section className="w-full max-w-sm rounded-3xl bg-[#fffdf9] p-6 shadow-xl"><h2 id="install-title" className="font-serif text-2xl">{copy.installInstructionsTitle}</h2><ol className="mt-4 space-y-2 text-sm"><li>{copy.installStepOne}</li><li>{copy.installStepTwo}</li><li>{copy.installStepThree}</li></ol><button type="button" autoFocus onClick={() => setOpen(false)} className="mt-6 rounded-full bg-[#255b48] px-4 py-2 text-sm font-semibold text-white">{copy.close}</button></section></div> : null}</>;
}
